jobs:
  buildDocker:
    name: build docker images
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout gatk
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        password: ${{ secrets.DOCKER_NIGHTLY_SERVICE_TOKEN }}
        registry: docker.io
        username: ${{ secrets.DOCKER_NIGHTLY_SERVICE_LOGIN }}
    - continue-on-error: true
      name: Export tags to env
      run: 'DATE=$(date +%Y-%m-%d);

        echo "DOCKER_NIGHTLY_TAG=${DATE}-$(git describe)-NIGHTLY-SNAPSHOT" >> $GITHUB_ENV

        echo "DOCKER_NIGHTLY_TAG_LATEST=latest" >> $GITHUB_ENV

        '
    - continue-on-error: true
      id: meta
      name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: broadinstitute/gatk-nightly
        tags: 'type=raw,value=${{env.DOCKER_NIGHTLY_TAG}}

          type=raw,value=${{env.DOCKER_NIGHTLY_TAG_LATEST}}

          '
    - continue-on-error: true
      name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        labels: ${{ steps.meta.outputs.labels }}
        push: false
        tags: ${{ steps.meta.outputs.tags }},
name: Build and Upload GATK Nightly Docker Image
on:
  repository_dispatch:
    types: trigger-ga___gatk-nightly-docker.yml
